# Generated by Django 3.2 on 2021-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_blockeddays_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
