# Generated by Django 3.2 on 2021-11-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20211124_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='check_out',
            field=models.DateField(),
        ),
    ]
